### ISSUE TITLE
Allow cross-stack reference to cognito App Client

### ISSUE THREAD

**Issue by MikeMather** [chrilliams/aws-amplify-exports-serverless-plugin#1]
Right now, the cognito userpool client has to be defined in the same service as the API Gateway. In my case, we have a separate stack for our Cognito resources that we export. I'd like to reference the app client using 
```
  amplify:
    - filename: ../../aws-exports/aws-exports.js
      type: javascript
      appClient: 
        Fn::ImportValue: CognitoUserPoolClient
```

Getting this error now when I deploy because it can't find the resource in the same stack:
```
ERROR: amplify-plugin: Cannot load resources: Invalid appClient specified: [object Object]
```
